export const questionnaires = [
  {
    questionId: 4927863,
    sequence: 1,
    elementType: "RADIO",
    mandatory: true,
    text: "Har du opplevd søvnproblemer?",
    answerOptions: [
      {
        answerOptionId: 11267478,
        sequence: 1,
        text: "Ikke plaget",
        externalAnswerOptionId: "1",
        preselected: false,
        correct: false,
      },
      {
        answerOptionId: 11267505,
        sequence: 2,
        text: "Lite plaget",
        externalAnswerOptionId: "2",
        preselected: false,
        correct: false,
      },
      {
        answerOptionId: 11267506,
        sequence: 3,
        text: "Ganske mye",
        externalAnswerOptionId: "3",
        preselected: false,
        correct: false,
      },
      {
        answerOptionId: 11267507,
        sequence: 4,
        text: "Veldig mye",
        externalAnswerOptionId: "4",
        preselected: false,
        correct: false,
      },
    ],
    externalQuestionId: "var1",
    sendAdditionalRecipientEmail: false,
    horizontal: false,
    rangeMarksShown: false,
    published: false,
    useForRedirectToForm: false,
  },
  {
    questionId: 4927877,
    sequence: 1,
    elementType: "RADIO",
    mandatory: true,
    text: "Har du opplevd plutselig frykt uten grunn?",
    answerOptions: [
      {
        answerOptionId: 11267508,
        sequence: 1,
        text: "Ikke plaget",
        externalAnswerOptionId: "1",
        preselected: false,
        correct: false,
      },
      {
        answerOptionId: 11267509,
        sequence: 2,
        text: "Lite plaget",
        externalAnswerOptionId: "2",
        preselected: false,
        correct: false,
      },
      {
        answerOptionId: 11267510,
        sequence: 3,
        text: "Ganske mye",
        externalAnswerOptionId: "3",
        preselected: false,
        correct: false,
      },
      {
        answerOptionId: 11267511,
        sequence: 4,
        text: "Veldig mye",
        externalAnswerOptionId: "4",
        preselected: false,
        correct: false,
      },
    ],
    externalQuestionId: "var2",
    sendAdditionalRecipientEmail: false,
    horizontal: false,
    rangeMarksShown: false,
    published: false,
    useForRedirectToForm: false,
  },
  {
    questionId: 4927878,
    sequence: 1,
    elementType: "RADIO",
    mandatory: true,
    text: "Har du følt deg matt eller svimmel?",
    answerOptions: [
      {
        answerOptionId: 11267512,
        sequence: 1,
        text: "Ikke plaget",
        externalAnswerOptionId: "1",
        preselected: false,
        correct: false,
      },
      {
        answerOptionId: 11267513,
        sequence: 2,
        text: "Lite plaget",
        externalAnswerOptionId: "2",
        preselected: false,
        correct: false,
      },
      {
        answerOptionId: 11267514,
        sequence: 3,
        text: "Ganske mye",
        externalAnswerOptionId: "3",
        preselected: false,
        correct: false,
      },
      {
        answerOptionId: 11267515,
        sequence: 4,
        text: "Veldig mye",
        externalAnswerOptionId: "4",
        preselected: false,
        correct: false,
      },
    ],
    externalQuestionId: "var3",
    sendAdditionalRecipientEmail: false,
    horizontal: false,
    rangeMarksShown: false,
    published: false,
    useForRedirectToForm: false,
  },
  {
    questionId: 4927879,
    sequence: 1,
    elementType: "RADIO",
    mandatory: true,
    text: "Har du klandret deg selv?",
    answerOptions: [
      {
        answerOptionId: 11267516,
        sequence: 1,
        text: "Ikke plaget",
        externalAnswerOptionId: "1",
        preselected: false,
        correct: false,
      },
      {
        answerOptionId: 11267517,
        sequence: 2,
        text: "Lite plaget",
        externalAnswerOptionId: "2",
        preselected: false,
        correct: false,
      },
      {
        answerOptionId: 11267518,
        sequence: 3,
        text: "Ganske mye",
        externalAnswerOptionId: "3",
        preselected: false,
        correct: false,
      },
      {
        answerOptionId: 11267519,
        sequence: 4,
        text: "Veldig mye",
        externalAnswerOptionId: "4",
        preselected: false,
        correct: false,
      },
    ],
    externalQuestionId: "var4",
    sendAdditionalRecipientEmail: false,
    horizontal: false,
    rangeMarksShown: false,
    published: false,
    useForRedirectToForm: false,
  },
];
